version: '3.9'

services:
  deal-db:
    image: postgres:16.9-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dealdb
    ports:
      - "5312:5432"

  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
