version: '3.9'

services:
  contractor-db:
    image: postgres:16.9-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dealdb
    ports:
      - "5312:5432"