server:
  port: 8002

spring:
  application:
    name: deal-service
  datasource:
    url: jdbc:postgresql://localhost:5312/dealdb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
