server:
  port: 8002

spring:
  application:
    name: deal-service
  datasource:
    url: jdbc:postgresql://localhost:5312/dealdb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true

jwt:
  secret: qO8zR9Avpm1FLzXzo1kS9OytZ+QjzUpgGzkhEwo6hH4=
  issuer: fintech-application
  expiration: 3600000 # 1 час
